// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjosdfpjiphivwlpttjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqb3NkZnBqaXBoaXZ3bHB0dGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Nzk3MDgsImV4cCI6MjA1ODE1NTcwOH0.ihyp9izvLq1Df8vAAVMEtTYCVHrEOX5pmPbDLScS54c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);